[Icon Theme]
Name=Conflux
Comment=Beautiful modern cohesive icon theme
Inherits=Adwaita,breeze,hicolor
Example=files

# KDE/Plasma Stuff
DisplayDepth=32
LinkOverlay=link_overlay
LockOverlay=lock_overlay
ZipOverlay=zip_overlay
DesktopDefault=48
DesktopSizes=16,22,32,48,64,96,128,256
ToolbarDefault=22
ToolbarSizes=16,22,32,48
MainToolbarDefault=22
MainToolbarSizes=16,22,32,48
SmallDefault=16
SmallSizes=16,22,32,48
PanelDefault=48
PanelSizes=16,22,32,48,64,96,128,256
DialogDefault=32
DialogSizes=16,22,32,48,64,128,256
FollowsColorScheme=true

KDE-Extensions=.svg

# Directory list
Directories=apps/scalable,devices/scalable,emblems/16,emblems/22,emblems/24,mimes/scalable,places/scalable,preferences/32,status/16,status/22,status/24,status/32,status/symbolic
ScaledDirectories=apps@2x/scalable,devices@2x/scalable,emblems@2x/16,emblems@2x/22,emblems@2x/24,mimes@2x/scalable,places@2x/scalable,preferences@2x/32,status@2x/16,status@2x/22,status@2x/24,status@2x/32,status@2x/symbolic

[apps/scalable]
Size=64
Context=Applications
MinSize=16
MaxSize=512
Type=Scalable

[devices/scalable]
Size=64
Context=Devices
MinSize=32
MaxSize=512
Type=Scalable

[emblems/16]
Size=16
Context=Emblems
Type=Fixed

[emblems/22]
Size=22
Context=Emblems
MinSize=16
MaxSize=96
Type=Scalable

[emblems/24]
Size=24
Context=Emblems
Type=Fixed

[mimes/scalable]
Size=64
Context=MimeTypes
MinSize=24
MaxSize=512
Type=Scalable

[places/scalable]
Size=64
Context=Places
MinSize=32
MaxSize=512
Type=Scalable

[preferences/32]
Size=32
Context=Applications
MinSize=32
MaxSize=256
Type=Scalable

[status/16]
Size=16
Context=Status
Type=Fixed

[status/22]
Size=22
Context=Status
Type=Fixed

[status/24]
Size=24
Context=Status
Type=Fixed

[status/32]
Size=32
Context=Status
MinSize=32
MaxSize=512
Type=Scalable

[status/symbolic]
Size=16
Context=Status
MinSize=16
MaxSize=512
Type=Scalable

# @2x

[apps@2x/scalable]
Size=64
Scale=2
Context=Applications
MinSize=16
MaxSize=512
Type=Scalable

[devices@2x/scalable]
Size=64
Scale=2
Context=Devices
MinSize=32
MaxSize=512
Type=Scalable

[emblems@2x/16]
Size=16
Scale=2
Context=Emblems
Type=Fixed

[emblems@2x/22]
Size=22
Scale=2
Context=Emblems
MinSize=16
MaxSize=96
Type=Scalable

[emblems@2x/24]
Size=24
Scale=2
Context=Emblems
Type=Fixed

[mimes@2x/scalable]
Size=64
Scale=2
Context=MimeTypes
MinSize=24
MaxSize=512
Type=Scalable

[places@2x/scalable]
Size=64
Scale=2
Context=Places
MinSize=32
MaxSize=512
Type=Scalable

[preferences@2x/32]
Size=32
Scale=2
Context=Applications
MinSize=32
MaxSize=256
Type=Scalable

[status@2x/16]
Size=16
Scale=2
Context=Status
Type=Fixed

[status@2x/22]
Size=22
Scale=2
Context=Status
Type=Fixed

[status@2x/24]
Size=24
Scale=2
Context=Status
Type=Fixed

[status@2x/32]
Size=32
Scale=2
Context=Status
MinSize=32
MaxSize=512
Type=Scalable

[status@2x/symbolic]
Size=16
Scale=2
Context=Status
MinSize=16
MaxSize=512
Type=Scalable